### PR TITLE
Adding the poster to women's section

### LINKED ISSUE #67: Adding a poster in women's section
### Issue Description

- Include a banner/poster related to women's footwear on the `women.html` page at the top of the page just below the navbar.
- Something like this
image
- Please share the screenshot while creating the PR

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

### PR DESCRIPTION
**Pull request by soumali28**
# 📝 Description

Added the poster part to the women's section of women.html file.

🔧 Fixes #67

<hr/>  

### 📷  Screenshot/Gifs of the part that I contributed.

Document - Google Chrome 10_2_2021 6_36_53 PM

<hr/>  

Document - Google Chrome 10_2_2021 6_37_34 PM
- [x] I have performed a self-review of my own code.
- [x] I'm a contributor in Hacktoberfest'21.

### CODE REVIEW

**Comment by saloni-15** [comment]
hey @soumali28, this looks very good, would you like to add a poster in the men's section too?

**Comment by soumali28** [comment]
@saloni-15 yeah sure ill add a poster to men's  sec too.

**Comment by saloni-15** [comment]
> @saloni-15 yeah sure ill add a poster to men's sec too.

@soumali28, I'll be updating the project structure, after that i'll raise an issue and will assign it to you.

**Comment by soumali28** [comment]
Ok sure

**Comment by saloni-15** [comment]
https://github.com/saloni-15/Heel2Toe/issues/75

you can check here the issue, and please comment there

**Comment by saloni-15** [comment]
leave is @soumali28, someone has commented now, but can you please work on fixing this
image
on sliding the page write, its overflowing...you can remove that heel icon just keeping the banner... see if you can fix and you can create another PR for the same.

**Comment by soumali28** [comment]
Ok ill work on it and try to fix it

**Comment by soumali28** [comment]
hey i have done it but its just one line of code should I do the pr?

**Pull request merged**
