### PR TITLE
directing url to id page (only applies to home page)

### PR DESCRIPTION
**Pull request by nurulramadhona**
# 📝 Description

Task I've done:

1. Creating jquery to replace page URL defined in href to its page ID (only applies to the home page). I replace all except CONTACT menu.

For example: 
I keep the link (href="men.html") defined as it
On home page: the page URL "men.html" will be directed to its page ID "index.html#men"
On other page: the page URL "men.html" will directed to its original URL "men.html"
(I'll provide screenshots below)

By using jquery, you can apply the same header (tab menus section) or footer to other pages as well without changing anything (in this case, link list).

2. Synchronizing ID in index.html as mentioned in jquery.

3. Updating "Explore More, View Trending, View Best Sellers" button's link in index.html.

If you accept these changes, please make notes to contributors to use same hyperlink for header and footer in the page they'll create or they've created (in case, you wanna add header and footer to all pages to make it similar with home page's look). They can copy header or footer link from index.html.

🔧 Fixes #(issue)
#73 
<hr/>  

### 📷 Provide related Screenshot/Gifs if any.

The pointer will show the actual link:

**HOME PAGE**
Screenshot_107
**TRENDING PAGE (other pages as well)**
Screenshot_108

<hr/>  

- [x] I have performed a self-review of my own code.
- [x] I'm a contributor in Hacktoberfest'21.

### CODE REVIEW

**Comment by saloni-15** [comment]
Hey, there's no need to redirect to ids, you can make all links redirect to the respective pages only, from homepage also, make the links at navbar and footer to redirect to particular pages, not ids.

**Comment by nurulramadhona** [comment]
I've removed the jquery to direct all links to particular pages (including home page) as you requested. Please check.

**Comment by nurulramadhona** [comment]
So, for the issue I've created. The tasks I've done are
1. Updating links on navbar and footer

Screenshot_111

2. Updating "Explore More, View Trending, View Best Sellers" button's link in index.html.

Screenshot_112

Sorry if I misunderstood what you asked before. I already fixed it on the last commit, so please check.

**Comment by saloni-15** [comment]
thankyou @nurulramadhona

**Pull request merged**
