### PR TITLE
Update card layout, footer, navbar menu and add .gitignore

### LINKED ISSUE #102: Enhancement : Update Bootstrap Card Styling and Footer Layout
### Issue Description

- Apply more modern style of bootstrap card and overlaying the description.
- Also I've refactor the code to use bootstrap standard grid styling.
- Adding css class shadow to provide more emphasis on details.

### Are you a Hacktoberfest'21 contributor

- [X] Yes, I'am Hacktoberfest'21 contributor

### PR DESCRIPTION
**Pull request by throwexceptions**
# 📝 Change DescriptionScreen Shot 2021-10-05 at 12 29 03 PM
- Update card layout.
- Footer layout
- Navbar Menu Shadow
- Add .gitignore

🔧 Fixes #102 

<hr/>  

### 📷 Provide related Screenshot/Gifs if any.

Card Layout:
Screen Shot 2021-10-05 at 12 29 03 PM
<hr/>  
Footer layout:
Screen Shot 2021-10-05 at 12 29 57 PM
<hr/>  
Navbar Menu Shadowing:
Screen Shot 2021-10-05 at 12 30 29 PM

<hr/>  
- [ ✔️ ] I have performed a self-review of my own code.
- [✔️  ] I'm a contributor in Hacktoberfest'21.

### CODE REVIEW

**Review by saloni-15 — CHANGES_REQUESTED** [review]
Hey, thank you for creating this PR. Everything looks good just don't make the changes in the card layout, leave it as it is, else the navbar and footer seem nice.

**Comment by throwexceptions** [comment]
Hi @saloni-15 ,

I've reverted the card layout to default bootstrap card.

Please see changes below screenshot:
Screen Shot 2021-10-05 at 12 29 03 PM

**Comment by saloni-15** [comment]
can you share the full page screenshot?

**Comment by throwexceptions** [comment]
Hi @saloni-15 ,

Please see below full page screenshot.

Screen Shot 2021-10-05 at 1 47 26 PM

**Review by saloni-15 — APPROVED** [review]
Thank you, it looks good.

**Pull request merged**
