### PR TITLE
Improve UI footer section

### LINKED ISSUE #1: Improve the Footer Section
**Show your creativity and change the UI for the footer.**

### PR DESCRIPTION
**Pull request by Sugyanee**
# 📝 Description

🔧Fixes  #1 
# Improved the UI of the footer section

<hr/>  

<hr/>  

- [x] I have performed a self-review of my own code.
- [x] I'm a contributor in Hacktoberfest'21.

### CODE REVIEW

**Comment by saloni-15** [comment]
resolve conflicts

**Comment by Sugyanee** [comment]
> resolve conflicts

done

**Comment by saloni-15** [comment]
thankyou @Sugyanee

**Comment by saloni-15** [comment]
image

hey,there's is still some issue, you can resolve this and make a new PR

**Comment by Sugyanee** [comment]
> image
> 
> hey,there's is still some issue, you can resolve this and make a new PR

Resolved!

**Pull request merged**
