### PR TITLE
style: improve-carousel-text

### PR DESCRIPTION
**Pull request by sarthakdelori**
# 📝 Description

Please include a summary of the change and which issue is fixed.

🔧 Fixes #(issue)
Issue #82: Updated the styling of the text of the carousel on the best seller page. The changes are made in best.html and best.css.

<hr/>  

### 📷 Provide related Screenshot/Gifs if any.

image

image

<hr/>  

- [x] I have performed a self-review of my own code.
- [x] I'm a contributor in Hacktoberfest'21.

### CODE REVIEW

**Review by saloni-15 — CHANGES_REQUESTED** [review]
hey, it looks good, but the main intention was to change the text styling, not to add some extra shapes so that it can look neat and clean, see if you can make something like that.

**Comment by sarthakdelori** [comment]
So, you want just the style of text to be changed in a way that it looks neat and clean? I think the problem that persist with that it is not looking readable after changing the text style, that's why I made some changes in the background too.

If this can help or I will go forward with some other changes.

**Comment by saloni-15** [comment]
see if you can do with the text only, or if not possible change the background shape to an oval rectangle like this
image

**Comment by dukeofwest** [comment]
Can you assign this task to me?

**Comment by saloni-15** [comment]
> Can you assign this task to me?

ya sure, but can you please comment on the issue  #82, so that I can assign you

**Pull request merged**
