### PR TITLE
modified bestseller.html page

### PR DESCRIPTION
**Pull request by salmangada**
# 📝 Description

I added the bestSeller.html page and modified it using carousel.

🔧 Fixes #(issue)

<hr/>  

### 📷 Provide related Screenshot/Gifs if any.

<hr/>  

- [ ] I have performed a self-review of my own code.
- [ ] I'm a contributor in Hacktoberfest'21.

### CODE REVIEW

**Comment by saloni-15** [comment]
can you just provide the screenshot for the same

**Comment by salmangada** [comment]
image

image

**Comment by saloni-15** [comment]
thankyou @salmangada

**Comment by salmangada** [comment]
Welcome.

**Pull request merged**
